### ISSUE TITLE
Improve version tracking tool

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd#41]
- [ ] Finish `update.py` script so it gather log data daily and stores it permanently in the S3 bucket to long term storage
- [ ] Add daily call to `update.py` to collect logs, generate graphs, and cleanup

Daily data collection should tabulate and graph the following and store these in `https://version.gridlabd.us/logs/`
- [ ] Daily usage (`MM/daily.csv` and `MM/daily.png`)
- [ ] Monthly usage (`YYYY/monthly.csv` and `YYYY/monthly.png`)
- [ ] Daily usage of branches (`YYYY/MM/daily_branch.csv` and `YYYY/MM/daily_branch.png`)
- [ ] Daily usage of branches by unique users (`YYYY/MM/daily_user.csv` and `YYYY/MM/daily_user.png`)
- [ ] Monthly usage of branches (`YYYY/monthly_branch.csv` and `YYYY/monthly_branch.png`)
- [ ] Monthly usage of branches by unique users (`YYYY/monthly_user.csv` and `YYYY/monthly_user.png`)
- [ ] Update `insights` tool so it uses results of `update.py` in `logs`.
